# Generated by Django 4.1.2 on 2022-11-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
