# Generated by Django 4.1.2 on 2022-11-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, default='photos/account.svg', null=True, upload_to='photos/'),
        ),
    ]
