# Generated by Django 4.1.2 on 2022-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, default='assets/photos/account.svg', null=True, upload_to='photos/'),
        ),
    ]
