# Generated by Django 4.1.2 on 2022-11-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_categorymodel_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
    ]
