# Generated by Django 4.1.2 on 2022-11-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='view_click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
