# Generated by Django 4.1.2 on 2022-11-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='media/'),
        ),
    ]
