# Generated by Django 4.1.2 on 2022-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, default='photos/account.svg', null=True, upload_to='photos/'),
        ),
    ]
