# Generated by Django 4.1.2 on 2022-11-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
