# Generated by Django 4.1.2 on 2022-11-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(default='user.jpg', upload_to='profile_pics'),
        ),
    ]
